services:
  - type: web
    name: kandahub
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn kandahub.wsgi:application
    preDeployCommand: python manage.py migrate
